# Marine Intelligence Platform - PRD

## Executive Summary

A React Native mobile app for Indian coastal fishermen providing **real-time safety assessment, marine intelligence, and fishing zone recommendations** through an AI-powered chat interface backed by deterministic marine data analysis.

**Not an LLM chatbot.** Every response is evidence-based with actual oceanographic data, weather conditions, and safety rules applied deterministically.

**Team:** MNV (Backend/Agents) + ARP (Mobile/Frontend)
**Platform:** React Native + Expo (iOS/Android)
**Duration:** 5-day hackathon

---

## 1. UNIQUE VALUE PROPOSITION (USP)

### For Fishermen:
- ✅ **Deterministic Safety** - Not opinions, but real IMD/INCOIS/Copernicus data
- ✅ **Before You Leave** - Ask "Can I fish tomorrow morning?" and get immediate risk assessment
- ✅ **Visual Risk Map** - See exactly where it's safe (green), risky (yellow), dangerous (red)
- ✅ **Geofencing Alerts** - Know when you're approaching restricted zones (international borders, MPAs)
- ✅ **Actionable Recommendations** - "Fishing is possible but avoid zones beyond X km"

### For Disaster Management:
- ✅ **Early Warning System** - Cyclone/high wave detection feeds directly into alerts
- ✅ **Marine Situational Awareness** - Real-time wind, waves, SST on interactive map
- ✅ **Geospatial Intelligence** - EEZ boundaries, maritime zones, protected areas
- ✅ **Decision Support** - Authorities can see risk distribution across fishing zones

### Technical Edge:
- ✅ **Hybrid Data Strategy** - Static 1-year baseline + daily API updates = anomaly detection
- ✅ **Offline-First** - Works with cached data even if APIs are down
- ✅ **Mobile-Native** - React Native for iOS + Android from single codebase
- ✅ **Safety-First Architecture** - Rules override LLM; implication explicit evidence chains

---

## 2. PRODUCT REQUIREMENTS

### 2.1 MVP Features (4 Screens)

#### Screen 1: Home / AI Chat
**Purpose:** Quick safety & fishing zone questions via conversational interface

**Capabilities:**
- Text input: "Can I go fishing tomorrow morning near Kochi?"
- System responds with:
  - **Risk Level** (LOW / MODERATE / HIGH)
  - **Raw Data Display:**
    - Wind speed (km/h)
    - Wave height (m)
    - Rainfall (mm)
    - Lightning status
    - Cyclone status
  - **Recommendation Text** (generated by Sarvam-105B, but grounded in real data)
  - **Evidence Trail:**
    - "Based on: Open-Meteo (6h ago), Copernicus (today), IMD (live)"
    - Confidence score (0-100%)
  - **Quick Action Button:** [View Risk Map]

**Technical Notes:**
- NOT real-time translation (keep MVP simple; use English)
- Input: Query text + user location (GPS or manual)
- Output: JSON with risk_level, conditions, recommendation, sources, map_data
- Response time: < 3 seconds (use cached data + fast inference)

---

#### Screen 2: Marine Map
**Purpose:** Visualize real-time marine conditions with layered intelligence

**Visual Layout:**
```
┌─────────────────────────────────────┐
│   MARINE INTELLIGENCE MAP           │
│   [Location: Kochi, IN]             │
│   ┌─────────────────────────────┐   │
│   │                             │   │
│   │   🟢  🟡         🔴         │   │
│   │                             │   │
│   │    ⚠ Cyclone Track          │   │
│   │                             │   │
│   │  🚫 Restricted Zone (EEZ)   │   │
│   │                             │   │
│   └─────────────────────────────┘   │
│                                     │
│  Layer Toggles:                     │
│  [SST] [Chlorophyll] [Wind]         │
│  [Waves] [PFZ] [Risk] [Geofence]    │
│                                     │
│  Legend:                            │
│  🟢 Low Risk  🟡 Moderate  🔴 High  │
└─────────────────────────────────────┘
```

**Layers:**
1. **Risk Heatmap** (0-100 score, color-coded)
2. **SST** (Sea Surface Temperature, 24-30°C)
3. **Chlorophyll** (Productivity 0-2 mg/m³)
4. **Wind** (Speed + direction arrows)
5. **Waves** (Wave height heatmap)
6. **PFZ Zones** (52 zones as polygon overlays)
7. **Geofence** (EEZ, maritime boundaries, MPAs in red)

**Interaction:**
- Tap a zone to see details (PFZ name, distance, conditions)
- Toggle layers on/off (disable for performance)
- Center on current location (GPS)
- Pan/zoom standard map controls

**Performance:**
- Tile-based rendering (don't render all 52 zones at once)
- Cache GeoJSON layers locally
- Lazy-load data layers

---

#### Screen 3: PFZ / Fishing Intelligence
**Purpose:** Show nearest high-confidence fishing zones with evidence

**Layout:**
```
┌────────────────────────────────────┐
│  FISHING ZONE INTELLIGENCE         │
│                                    │
│  Nearest Zone (18.4 km away)       │
│  ┌──────────────────────────────┐  │
│  │  📍 Zone Name: Kochi Bank-A  │  │
│  │  🌊 SST: 27.2°C              │  │
│  │  🟢 Chlorophyll: 1.82 mg/m³  │  │
│  │  ⭐ Confidence: 87%           │  │
│  │                              │  │
│  │  Why this zone?              │  │
│  │  ✓ High chlorophyll          │  │
│  │  ✓ Suitable SST (25-30°C)    │  │
│  │  ✓ Historical data: 8500 ton/yr│
│  │  ✓ Low wind today            │  │
│  │                              │  │
│  │  [View on Map] [Get Route]   │  │
│  └──────────────────────────────┘  │
│                                    │
│  Other Zones (Top 5)               │
│  ├─ Zone B: 24.1 km (81% conf)    │
│  ├─ Zone C: 31.2 km (76% conf)    │
│  └─ ...                           │
└────────────────────────────────────┘
```

**Data Shown:**
- Zone name + distance
- SST (from Copernicus)
- Chlorophyll (from Copernicus)
- Confidence score (how certain about productivity)
- Why this zone is good (evidence bullets)
- Historical productivity (from CMFRI data)
- Top 5 ranked zones (scrollable)

**Actions:**
- Tap zone → show on map + center
- [Get Route] → opens routing to zone
- [View Details] → historical trends, monthly patterns

---

#### Screen 4: Safety / Alerts
**Purpose:** Display real-time marine safety warnings and geofencing alerts

**Alert Types:**

**A. Weather/Ocean Alerts**
```
┌────────────────────────────────────┐
│  ⚠ MARINE ALERT                    │
│                                    │
│  High Wave Conditions Detected     │
│  near your selected zone           │
│                                    │
│  Wave Height: 3.4 m               │
│  Wind Speed: 42 km/h              │
│  Recommended Action: AVOID         │
│                                    │
│  Status: Updated 30 mins ago       │
│  Source: Open-Meteo, IMD           │
│                                    │
│  [Acknowledge] [View Map]          │
└────────────────────────────────────┘
```

**B. Geofencing Alerts**
```
┌────────────────────────────────────┐
│  ⚠ GEOFENCING ALERT                │
│                                    │
│  You are approaching a             │
│  Restricted Marine Zone            │
│                                    │
│  Zone Type: India-Pakistan Border  │
│  Distance: 2.1 km                  │
│  Action: TURN BACK                 │
│                                    │
│  [View Boundary] [Get Safe Route]  │
└────────────────────────────────────┘
```

**C. Cyclone/Safety Warnings**
```
┌────────────────────────────────────┐
│  🔴 CYCLONE ALERT                   │
│                                    │
│  DO NOT VENTURE OUT                │
│                                    │
│  Cyclone: Low Pressure System      │
│  Movement: NW @ 15 km/h            │
│  ETA: 24 hours                     │
│  Status: IMD Alert Level 3         │
│                                    │
│  [More Info] [Contact Authority]   │
└────────────────────────────────────┘
```

**Alert Feed:**
- Stack of alerts by urgency (red > yellow > blue)
- Each card dismissible with [Acknowledge]
- Persistent banner for critical alerts (cyclone)
- Alert history (scroll to see older alerts)

**Types of Alerts to Show:**
1. Cyclone/severe weather (IMD)
2. High waves (Open-Meteo)
3. High wind (Open-Meteo)
4. Lightning warnings (IMD)
5. Geofencing (boundaries crossed)
6. Chlorophyll anomalies (sudden drop = fishing unlikely)

---

### 2.2 Out of Scope (Phase 2+)

- Voice input/output (Sarvam STT/TTS)
- Multilingual UI (only English MVP)
- User accounts / login
- Trip logging / history
- Social features
- ML-based PFZ prediction (use rules-based for now)
- Advanced routing (A* pathfinding - nice to have)

---

## 3. ARCHITECTURE

### 3.1 System Diagram

```
┌───────────────────────────────┐
│   React Native App (Expo)     │
│   ┌──────────────┐            │
│   │  Chat Screen │ ────┐      │
│   ├──────────────┤     │      │
│   │  Map Screen  │     │      │
│   ├──────────────┤     │      │
│   │  PFZ Screen  │     │      │
│   ├──────────────┤     │      │
│   │ Alert Screen │     │      │
│   └──────────────┘     │      │
│        Local Cache     │      │
│   (GeoJSON, 1yr data)  │      │
└───────────────────────────────┘
         ↓ HTTPS ↓
┌───────────────────────────────┐
│    FastAPI Backend            │
│    (:8000)                    │
│                               │
│  ┌─────────────────────────┐  │
│  │  LangGraph Agents       │  │
│  │  ┌──────────────────┐   │  │
│  │  │ 1. Planner       │   │  │
│  │  │ 2. Data          │   │  │
│  │  │ 3. Geo/Risk      │   │  │
│  │  │ 4. Response      │   │  │
│  │  └──────────────────┘   │  │
│  └─────────────────────────┘  │
│                               │
│  API Endpoints:               │
│  POST /chat                   │
│  GET  /geojson/*              │
│  GET  /alerts                 │
│  GET  /pfz/nearest            │
│  GET  /risk/assess            │
└───────────────────────────────┘
         ↓ HTTPS ↓
┌───────────────────────────────┐
│   External Data APIs          │
│  ┌──────────────────────────┐ │
│  │ Copernicus (SST/Chl)     │ │
│  │ Open-Meteo (Wind/Waves)  │ │
│  │ IMD (Cyclone/Weather)    │ │
│  └──────────────────────────┘ │
└───────────────────────────────┘
```

### 3.2 Tech Stack

| Layer | Technology | Purpose |
|-------|-----------|---------|
| **Mobile** | React Native + Expo | iOS/Android app |
| **Navigation** | React Navigation | Screen stack + tabs |
| **Maps** | react-native-maps + GeoJSON | Interactive marine map |
| **Charts/Data** | react-native-svg | Risk visualization |
| **State** | Redux or Zustand | Chat, alerts, map state |
| **HTTP** | axios | API calls to backend |
| **Local Storage** | AsyncStorage | Cached GeoJSON, user prefs |
| **Backend** | FastAPI + Python | Agent orchestration |
| **Agents** | LangGraph | Multi-node reasoning |
| **LLM** | Sarvam-105B | Chat responses |
| **Geospatial** | GeoPandas, Shapely | Boundary checks, distance |
| **Database** | SQLite (local) | PFZ zones, historical data |
| **APIs** | Copernicus, Open-Meteo, IMD | Live data |

---

## 4. DESIGN DECISIONS

### 4.1 Why React Native?

- ✅ Single codebase iOS + Android
- ✅ Fast to prototype (Expo)
- ✅ Large community for maps + native modules
- ✅ Suitable for offline-first (AsyncStorage)

### 4.2 Why Deterministic Rules > ML?

- ✅ Safety-critical: fishermen's lives matter
- ✅ Transparent: explain why (evidence-based)
- ✅ Faster: no model inference latency
- ✅ Reliable: rules don't hallucinate

### 4.3 Why 4 Screens?

- ✅ **Chat** - Quick QA (not chatbot, but evidence-based)
- ✅ **Map** - Visual intelligence (core value)
- ✅ **PFZ** - Fishing recommendations (domain-specific)
- ✅ **Alerts** - Safety warnings (critical for disaster mgmt)

Simple enough for 5-day hackathon. Powerful enough for real use.

### 4.4 Why Static + Dynamic Data?

**Static (88.6 MB local):**
- 1 year of SST/Chlorophyll (baseline)
- 52 PFZ zones
- Boundaries, landing centers
- 10 years of fish catch history

**Dynamic (6-hourly API):**
- Today's SST (Copernicus)
- Today's Chlorophyll (Copernicus)
- Today's wind/waves (Open-Meteo)
- Live cyclone/weather (IMD)

**Why:** Anomaly detection. "Today's Chl is 2x normal = high alert."

### 4.5 Offline-First Design

- App loads with cached data immediately
- API calls update data in background
- If APIs down, app still functional (stale but safe)
- Local GeoJSON stored in AsyncStorage

---

## 5. DATA FLOW

### Chat Flow
```
User: "Can I fish tomorrow morning?"
    ↓
[Mobile] Extract: Location (Kochi), Time (tomorrow, morning)
    ↓ POST /chat
[Backend Planner Agent]
    - Detect intent: SAFETY_CHECK
    - Extract: lat=8.5, lon=77.5, time=tomorrow_0600
    ↓
[Backend Data Agent]
    - Fetch Open-Meteo: wind, waves for tomorrow
    - Fetch Copernicus: SST today, Chl today
    - Fetch IMD: cyclone forecast
    - Load static: 1-year baseline for comparison
    ↓
[Backend Risk Agent]
    - Apply rules: wind<25kt? wave<3m? cyclone=no?
    - Score: 0-100
    - If score >= 70: SAFE; 40-69: MODERATE; <40: HIGH
    ↓
[Backend Response Agent]
    - Sarvam: "Fishing is possible but avoid zones beyond X km"
    - Evidence: "Wind 18km/h (safe), Wave 1.8m (ok), Chl 0.85 (good)"
    - Confidence: 87%
    ↓ JSON Response
[Mobile] Display:
    - Risk Level card (RED/YELLOW/GREEN)
    - Conditions list (wind, waves, rain, etc.)
    - Recommendation text
    - Evidence trail (sources)
    - [View Risk Map] button
```

### Map Flow
```
User: Tap Map Tab
    ↓
[Mobile] Load cached layers:
    - PFZ zones (GeoJSON, 52 zones)
    - Boundaries (GeoJSON)
    ↓ GET /geojson/risk
[Mobile] Fetch today's risk heatmap
    ↓
[Mobile] Render:
    - Basemap (OSM)
    - Risk heatmap overlay (colors by risk score)
    - Layer toggles (checkboxes)
    ↓
User: Toggle "SST" layer
    ↓
[Mobile] GET /geojson/sst
    ↓
[Mobile] Overlay: SST raster (blue=cold, red=hot)
```

---

## 6. DATA SOURCES & FRESHNESS

| Data | Source | Static? | Dynamic? | Frequency | Latency |
|------|--------|---------|----------|-----------|---------|
| PFZ Zones | INCOIS | ✅ 52 zones (0.5MB) | ❌ | - | - |
| Boundaries | Govt data | ✅ (3MB) | ❌ | - | - |
| Chlorophyll | Copernicus | ✅ 1yr (50MB) | ✅ Daily | Daily | +1 day |
| SST | Copernicus | ✅ 1yr (30MB) | ✅ Daily | Daily | +1 day |
| Wind/Waves | Open-Meteo | ❌ | ✅ | 6-hourly | Real-time |
| Cyclone/Weather | IMD | ❌ | ✅ | 6-hourly | Real-time |
| Fish Catch | CMFRI | ✅ 10yr (5MB) | ❌ | Quarterly | - |

---

## 7. SUCCESS METRICS (End of Day 5)

- ✅ Chat responds with risk level + raw data in < 3 sec
- ✅ Map displays PFZ zones + risk heatmap
- ✅ PFZ screen shows nearest 5 zones with confidence
- ✅ Alerts display for geofencing + weather
- ✅ App works offline with cached data
- ✅ Deployable APK/IPA
- ✅ 5-min demo ready

---

## 8. RISKS & MITIGATIONS

| Risk | Mitigation |
|------|-----------|
| Map rendering slow with 52 zones | Tile-based, cluster polygons, lazy-load |
| Copernicus/IMD APIs down | Use cached data, add fallback mocks |
| React Native maps library issues | Use react-native-maps (proven in prod) |
| Battery drain from GPS polling | Only fetch on app foreground |
| APK size too large | Tree-shake, remove unused deps |

---

**Document Version:** 1.0
**Platform:** React Native (Expo)
**Status:** Ready for Development

